export const CHANGE_TERM = "CHANGE_TERM";
export const SEARCH_TERM = "SEARCH_TERM";
export const SEARCH_SENTIMENT = "SEARCH_SENTIMENT";
export const COMBINE_SENTIMENT = "COMBINE_SENTIMENT";
export const ADD_SAVED_CHART = "ADD_SAVED_CHART";